name: Run Build All
on:
  - push
  - pull_request

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.1.1

      - name: Setup Java
        uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make build.sh executable
        run: chmod +x build.sh

      - name: Execute Build All
        run: ./build.sh

      - name: List build directory contents
        if: ${{ always() }}
        run: ls -R build

      - name: List badjars directory contents
        if: ${{ always() }}
        run: ls -R build/badjars

      - name: Upload built mod JAR
        uses: actions/upload-artifact@v4.3.0
        with:
          name: mod-jar
          path: build/libs/*.jar
      - name: Install curl
        run: sudo apt-get install -y curl

      - name: Send to Discord webhook
        run: |
          for file in build/libs/*.jar; do
            curl -F "payload_json={\"content\":\"New build: $file\"}" -F "file=@$file" ${{ secrets.DISCORD_WEBHOOK_URL }}
          done
