name: Run Build All
on:
  - push
  - pull_request

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.1.1

      - name: Setup Java
        uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make build.sh executable
        run: chmod +x build.sh

      - name: Execute Build All
        run: ./build.sh

      - name: Upload built mod JAR
        uses: actions/upload-artifact@v4.3.0
        with:
          name: built-jars
          path: build/libs/*.jar
